"""
SQLAlchemy 2.0 ORM models for PRISON telemetry, attack graphs, and agent triage.
"""

from datetime import datetime, timezone
import uuid
from typing import Any, Dict, List, Optional
from sqlalchemy import BigInteger, Boolean, DateTime, Float, Integer, String, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column

from packages.db.connection import Base


def generate_uuid() -> str:
    return str(uuid.uuid4())


class TelemetryEventModel(Base):
    """
    Normalized telemetry system event ingested from OSEN eBPF probes.
    """
    __tablename__ = "telemetry_events"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    execution_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    pid: Mapped[int] = mapped_column(Integer, nullable=False)
    ppid: Mapped[int] = mapped_column(Integer, nullable=False)
    comm: Mapped[str] = mapped_column(String(255), nullable=False)
    syscall: Mapped[str] = mapped_column(String(64), nullable=False)
    args: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)
    honeypot_hit: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    risk_level: Mapped[str] = mapped_column(String(32), default="CLEAN", nullable=False)


class ExecutionGraphModel(Base):
    """
    Serialized DAG representing process execution hierarchy and risk classification.
    """
    __tablename__ = "execution_graphs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    execution_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    nodes: Mapped[List[Dict[str, Any]]] = mapped_column(JSON, default=list, nullable=False)
    edges: Mapped[List[Dict[str, Any]]] = mapped_column(JSON, default=list, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )


class ThreatReportModel(Base):
    """
    ANAKIN AI Agent triage evaluation output.
    """
    __tablename__ = "threat_reports"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    execution_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    threat_detected: Mapped[bool] = mapped_column(Boolean, nullable=False)
    severity_score: Mapped[int] = mapped_column(Integer, nullable=False)  # 0 to 100
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)  # 0.0 to 1.0
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    attack_vector: Mapped[str] = mapped_column(Text, nullable=False)
    compromised_files: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    suggested_action: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )


class RemediationPatchModel(Base):
    """
    Automated Git security patches generated by ANAKIN.
    """
    __tablename__ = "remediation_patches"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    execution_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    target_file: Mapped[str] = mapped_column(String(512), nullable=False)
    unified_diff: Mapped[str] = mapped_column(Text, nullable=False)
    branch_name: Mapped[str] = mapped_column(String(255), nullable=False)
    github_pr_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    status: Mapped[str] = mapped_column(String(32), default="PENDING", nullable=False)  # PENDING, BRANCH_CREATED, PR_COMMENTED
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
